# Model configuration
sentiment_model:
  name: finiteautomata/bertweet-base-sentiment-analysis
  save_model_path: resources/
  results_path: results/sentiment_analysis/

intent_model:
  name: facebook/bart-large-mnli
  save_model_path: resources/
  results_path: results/intent_prediction/
  intents:
  - greeting
  - order
  - thanking
  - preference
  - information
  - question

# Chatbot conversation data
example_data: data/simulated_conversation_1.json


